name: CI/CD Monitoring

on:
  workflow_run:
    workflows: ["CI/CD Pipeline", "Security & Assets"]
    types:
      - completed

jobs:
  monitor:
    name: Monitor CI/CD Results
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main' }}
    
    steps:
    - name: Create failure issue
      uses: actions/github-script@v7
      with:
        script: |
          const workflowRun = ${{ toJSON(github.event.workflow_run) }};
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `🚨 CI/CD Failure: ${workflowRun.name}`,
            body: `
            ## CI/CD Pipeline Failure
            
            **Workflow**: ${workflowRun.name}
            **Branch**: ${workflowRun.head_branch}
            **Commit**: ${workflowRun.head_sha.substring(0, 7)}
            **Run URL**: ${workflowRun.html_url}
            
            Please investigate and fix the failing workflow.
            `,
            labels: ['ci-failure', 'bug']
          });